### ISSUE TITLE
toInt is not defined

### ISSUE THREAD

**Issue by diondavidson** [allenhwkim/angular-template#20]
Am I missing a reference?
`c:\Users\DDavidson\node_modules\angular-template\index.js:95
        throw e;
        ^

ReferenceError: toInt is not defined
    at jsonStringToDate (c:\Users\DDavidson\node_modules\angular-template\pipes\date.js:128:16)
    at Function.module.exports (c:\Users\DDavidson\node_modules\angular-template\pipes\date.js:72:53)
    at eval (eval at templateFunc (c:\Users\DDavidson\node_modules\js-template\index.js:55:12), <anonymous>:3:255)
    at jsTemplate (c:\Users\DDavidson\node_modules\js-template\index.js:66:18)
    at angularTemplate (c:\Users\DDavidson\node_modules\angular-template\index.js:83:14)
`

**Comment by FDIM** [comment]
Thanks for reporting, this is fixed in v2.3.3
